
services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn expense_tracker.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString
databases:
  - name: expense-db
    databaseName: expense_db
    user: expense_user
